apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp3-deployment
spec:
replicas: 3
selector:
  matchlables:
    app: myapp3
template:
  metadata:
    name: myapp3-deploy
    labels:
    app: myapp3
  spec:
    container:
    - name: myapp3-container
      image: stackimplify/kubenginx:3.0.0
      ports: 
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: Deployment-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp3
    ports:
    - name: http
      port: 80 # service port
      targetPort: 80 # container port
