apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
  labels:
    app: backend-app
    tier: backend 
spec:
  replicas: 3
  selector:
    matctlabels:
      app: backend-restapp
  template:
   metadata:
    name: backend-restapp
    labels:
    app: backend-app
    tier: backend 
  spec:
    container:
      - name: backend-restapp
        image: stacksimplify/kube-helloworld:10.0.0
        port: 
          - containerPort: 8080










