apiVersion: v1
kind: Service
metadata:
  name:  frontend-nginxapp-loadbalancer-service
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  selector:
    app:  frontend-nginxapp
  type: LoadBalancer 
  ports:
   - name: http
      port: 80 # service port
      targetPort: 80 # container port