apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: azure-managed-pvc
spec:
  accessMode:
  - ReadWriteOnce
  atorageClassName: managed-premium-retain-sc
  resources:
    requests:
      storage: 5Gi