apiVersion: v1
kind: kind: Service
metadata:
  name:  my-backend-service
  labels:
    app: backend-app
    tier: backend 
spec:
  selector:
    app:  backend-restapp
  type: ClusterIP 
  ports:
   - name: http
      port: 8080 # service port
      targetPort: 8080 # container port




