apiVersion: apps/v1
kind: replicaset
metadata: #Dictoionary
  name: myapp2-rs
spec: #Dictoionary
  replicas: 3
  selector: 
    matclabels:
      app: myapp2
  template: #pod template ie specifications
    metadata:
    name: myapp2-pod 
    labels:
      app: myapp2  
  spec:
    containers:
      - name: myapp2-container
        image: stackimplify/kubenginx:2.0.0
        Ports:
          - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp2
    ports:
    - name: http
      port: 80 # service port
      targetPort: 80 # container port
